### ISSUE TITLE
Interesting but error with %store

### ISSUE THREAD

**Issue by RicRock** [outlier89/pybidbot#1]
Hello,

I ran across your bot and find it very interesting.

I'm newish to python and having a syntax error with the %store lines.

What does %store do? is it specific to Ipython?

**Comment by outlier89** [comment]
%store is used to pass the variable to another script. Here it is passing the variable to "api" script. %store works only with Ipython interpreter. What you can do is save the script as either .ipy or .ipynb and run either in jupyter notebook or in command line using: ipython <script name>.ipy
